/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hirain_sdk_rtsp_JNIDeviceStream */

#ifndef _Included_com_hirain_sdk_rtsp_JNIDeviceStream
#define _Included_com_hirain_sdk_rtsp_JNIDeviceStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hirain_sdk_rtsp_JNIDeviceStream
 * Method:    init
 * Signature: (Lcom/hirain/sdk/entity/rtsp/LocalConfig;)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_rtsp_JNIDeviceStream_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_hirain_sdk_rtsp_JNIDeviceStream
 * Method:    rtspStream
 * Signature: (Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_rtsp_JNIDeviceStream_rtspStream
  (JNIEnv *, jobject, jstring, jobject, jstring, jstring, jstring, jobject);

/*
 * Class:     com_hirain_sdk_rtsp_JNIDeviceStream
 * Method:    rtspSlice
 * Signature: (Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_rtsp_JNIDeviceStream_rtspSlice
  (JNIEnv *, jobject, jstring, jobject, jstring);

/*
 * Class:     com_hirain_sdk_rtsp_JNIDeviceStream
 * Method:    rtspSliceAutoStop
 * Signature: (Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;ILjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_rtsp_JNIDeviceStream_rtspSliceAutoStop
  (JNIEnv *, jobject, jstring, jobject, jstring, jint, jobject);

/*
 * Â¼Ïñ
 * Class:     com_hirain_sdk_rtsp_JNIDeviceStream
 * Method:    rtspSliceFrame
 * Signature: (Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;ILjava/lang/Object;I)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_rtsp_JNIDeviceStream_rtspSliceFrame
  (JNIEnv *, jobject, jstring, jobject, jstring, jint, jobject, jint);

/*
 * Class:     com_hirain_sdk_rtsp_JNIDeviceStream
 * Method:    sliceStream
 * Signature: (Ljava/lang/String;ILjava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_rtsp_JNIDeviceStream_sliceStream
  (JNIEnv *, jobject, jstring, jint, jobject, jstring, jstring, jstring);

/*
 * Class:     com_hirain_sdk_rtsp_JNIDeviceStream
 * Method:    sliceStreamPlay
 * Signature: (Ljava/lang/String;ILjava/lang/Object;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_rtsp_JNIDeviceStream_sliceStreamPlay
  (JNIEnv *, jobject, jstring, jint, jobject, jobject, jstring, jstring);

/*
 * Class:     com_hirain_sdk_rtsp_JNIDeviceStream
 * Method:    rtspStreamDirect
 * Signature: (Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_rtsp_JNIDeviceStream_rtspStreamDirect
  (JNIEnv *, jobject, jstring, jobject, jstring, jstring);

/*
 * Class:     com_hirain_sdk_rtsp_JNIDeviceStream
 * Method:    playStream
 * Signature: (Ljava/lang/String;ILjava/lang/Object;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_rtsp_JNIDeviceStream_playStream
  (JNIEnv *, jobject, jstring, jint, jobject, jobject, jstring, jstring);

/*
 * Class:     com_hirain_sdk_rtsp_JNIDeviceStream
 * Method:    sliceStreamH265ToH264Play
 * Signature: (Ljava/lang/String;ILjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_rtsp_JNIDeviceStream_sliceStreamH265ToH264Play
  (JNIEnv *, jobject, jstring, jint, jobject, jstring, jstring);

/*
 * Class:     com_hirain_sdk_rtsp_JNIDeviceStream
 * Method:    tcpStreamDirect
 * Signature: (Ljava/lang/String;ILjava/lang/Object;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_rtsp_JNIDeviceStream_tcpStreamDirect
  (JNIEnv *, jobject, jstring, jint, jobject, jstring, jstring);

/*
 * Class:     com_hirain_sdk_rtsp_JNIDeviceStream
 * Method:    tcpSliceAutoStop
 * Signature: (Ljava/lang/String;ILjava/lang/Object;Ljava/lang/String;ILjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_rtsp_JNIDeviceStream_tcpSliceAutoStop
  (JNIEnv *, jobject, jstring, jint, jobject, jstring, jint, jobject);

/*
 * Class:     com_hirain_sdk_rtsp_JNIDeviceStream
 * Method:    snapshoot
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_rtsp_JNIDeviceStream_snapshoot
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
