/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hirain_sdk_gb28181_JNIGB28181Client */

#ifndef _Included_com_hirain_sdk_gb28181_JNIGB28181Client
#define _Included_com_hirain_sdk_gb28181_JNIGB28181Client
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hirain_sdk_gb28181_JNIGB28181Client
 * Method:    uninit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hirain_sdk_gb28181_JNIGB28181Client_uninit
  (JNIEnv *, jobject);

/*
 * Class:     com_hirain_sdk_gb28181_JNIGB28181Client
 * Method:    test
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_gb28181_JNIGB28181Client_test
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_hirain_sdk_gb28181_JNIGB28181Client
 * Method:    play
 * Signature: (Lcom/hirain/sdk/entity/gb28181/Operation;)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_gb28181_JNIGB28181Client_play
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_hirain_sdk_gb28181_JNIGB28181Client
 * Method:    stop
 * Signature: (Lcom/hirain/sdk/entity/gb28181/Operation;)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_gb28181_JNIGB28181Client_stop
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_hirain_sdk_gb28181_JNIGB28181Client
 * Method:    record
 * Signature: (Lcom/hirain/sdk/entity/gb28181/Operation;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_gb28181_JNIGB28181Client_record
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_hirain_sdk_gb28181_JNIGB28181Client
 * Method:    control
 * Signature: (Lcom/hirain/sdk/entity/gb28181/Operation;)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_gb28181_JNIGB28181Client_control
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_hirain_sdk_gb28181_JNIGB28181Client
 * Method:    snapshoot
 * Signature: (Lcom/hirain/sdk/entity/gb28181/Operation;)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_gb28181_JNIGB28181Client_snapshoot
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
