/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hirain_sdk_rtmp_JNIRtmp */

#ifndef _Included_com_hirain_sdk_rtmp_JNIRtmp
#define _Included_com_hirain_sdk_rtmp_JNIRtmp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hirain_sdk_rtmp_JNIRtmp
 * Method:    createChannel
 * Signature: (Lcom/hirain/sdk/JNIEntity/RtmpChannelParam;)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_rtmp_JNIRtmp_createChannel
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_hirain_sdk_rtmp_JNIRtmp
 * Method:    destoryChannel
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_rtmp_JNIRtmp_destoryChannel
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
