/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hirain_sdk_rtsp_JNIPTZ */

#ifndef _Included_com_hirain_sdk_rtsp_JNIPTZ
#define _Included_com_hirain_sdk_rtsp_JNIPTZ
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hirain_sdk_rtsp_JNIPTZ
 * Method:    ONVIFPTZControlMove
 * Signature: (Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_rtsp_JNIPTZ_ONVIFPTZControlMove
  (JNIEnv *, jobject, jstring, jobject, jstring, jstring, jobject);

/*
 * Class:     com_hirain_sdk_rtsp_JNIPTZ
 * Method:    ONVIFAddPresetPoint
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hirain_sdk_rtsp_JNIPTZ_ONVIFAddPresetPoint
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_hirain_sdk_rtsp_JNIPTZ
 * Method:    ONVIFRemovePresetPoint
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_rtsp_JNIPTZ_ONVIFRemovePresetPoint
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_hirain_sdk_rtsp_JNIPTZ
 * Method:    ONVIFGetDefaultPresetPoint
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_hirain_sdk_rtsp_JNIPTZ_ONVIFGetDefaultPresetPoint
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_hirain_sdk_rtsp_JNIPTZ
 * Method:    ONVIFControlPresetPoint
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;F)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_rtsp_JNIPTZ_ONVIFControlPresetPoint
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jfloat);

/*
 * Class:     com_hirain_sdk_rtsp_JNIPTZ
 * Method:    ONVIFControlWiperAndLamp
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_rtsp_JNIPTZ_ONVIFControlWiperAndLamp
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_hirain_sdk_rtsp_JNIPTZ
 * Method:    ONVIFFocus
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;F)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_rtsp_JNIPTZ_ONVIFFocus
  (JNIEnv *, jobject, jstring, jstring, jstring, jfloat);

/*
 * Class:     com_hirain_sdk_rtsp_JNIPTZ
 * Method:    ONVIFStopFocus
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hirain_sdk_rtsp_JNIPTZ_ONVIFStopFocus
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
